usb: phy: phy-exynos-usb3p1: fix missing prototypes and reenable -Wmissing-prototypes
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:870:6: error: no previous prototype for ‘phy_exynos_usb_v3p1_ssp_cal_cr_write’ [-Werror=missing-prototypes]
      870 | void phy_exynos_usb_v3p1_ssp_cal_cr_write(struct exynos_usbphy_info *info,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:877:5: error: no previous prototype for ‘phy_exynos_usb_v3p1_ssp_cal_cr_read’ [-Werror=missing-prototypes]
      877 | u16 phy_exynos_usb_v3p1_ssp_cal_cr_read(struct exynos_usbphy_info *info,
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:884:6: error: no previous prototype for ‘phy_exynos_usb_v3p1_cal_usb3phy_tune_fix_rxeq’ [-Werror=missing-prototypes]
      884 | void phy_exynos_usb_v3p1_cal_usb3phy_tune_fix_rxeq(struct exynos_usbphy_info
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:969:6: error: no previous prototype for ‘phy_exynos_usb_v3p1_cal_usb3phy_tune_adaptive_eq’ [-Werror=missing-prototypes]
      969 | void phy_exynos_usb_v3p1_cal_usb3phy_tune_adaptive_eq(struct exynos_usbphy_info
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:985:6: error: no previous prototype for ‘phy_exynos_usb_v3p1_usb3phy_tune_chg_rxeq’ [-Werror=missing-prototypes]
      985 | void phy_exynos_usb_v3p1_usb3phy_tune_chg_rxeq(struct exynos_usbphy_info *info,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:1183:4: error: no previous prototype for ‘phy_exynos_usb3p1_get_phyclkcnt’ [-Werror=missing-prototypes]
     1183 | u8 phy_exynos_usb3p1_get_phyclkcnt(struct exynos_usbphy_info *info)
          |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:1199:4: error: no previous prototype for ‘phy_exynos_usb3p1_get_linestate’ [-Werror=missing-prototypes]
     1199 | u8 phy_exynos_usb3p1_get_linestate(struct exynos_usbphy_info *info)
          |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:1958:6: error: no previous prototype for ‘phy_exynos_usb3p1_usb3phy_dp_altmode_set_ss_disable’ [-Werror=missing-prototypes]
     1958 | void phy_exynos_usb3p1_usb3phy_dp_altmode_set_ss_disable(struct exynos_usbphy_info
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:1983:6: error: no previous prototype for ‘phy_exynos_usb3p1_usb3phy_dp_altmode_clear_ss_disable’ [-Werror=missing-prototypes]
     1983 | void phy_exynos_usb3p1_usb3phy_dp_altmode_clear_ss_disable(struct exynos_usbphy_info
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:2032:4: error: no previous prototype for ‘phy_exynos_usb3p1_get_fs_vplus_vminus’ [-Werror=missing-prototypes]
     2032 | u8 phy_exynos_usb3p1_get_fs_vplus_vminus(struct exynos_usbphy_info *info)
          |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:2045:6: error: no previous prototype for ‘phy_exynos_usb3p1_set_fsv_out_en’ [-Werror=missing-prototypes]
     2045 | void phy_exynos_usb3p1_set_fsv_out_en(struct exynos_usbphy_info *usbphy_info,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .../drivers/phy/samsung/phy-exynos-usb3p1.c:2128:1: error: no previous prototype for ‘phy_exynos_usb3p1_bc_battery_charger_detection’ [-Werror=missing-prototypes]
     2128 | phy_exynos_usb3p1_bc_battery_charger_detection(struct exynos_usbphy_info
          | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

... and it turns out most of these are not used anywhere, so just
remove them.

Bug: 330718746
Test: TH
Change-Id: I802954924a5a4adaaff0d041f4dce0947bf38c50
Signed-off-by: André Draszik <andre.draszik@linaro.org>
Signed-off-by: Aarqw12 <lcockx@protonmail.com>

# Conflicts:
#	drivers/phy/samsung/Kbuild